import type { NextPage } from "next";
import { useEffect } from "react";
import Head from "next/head";
import { Button } from "antd";
import { useActiveWeb3React } from "hooks/useActiveWeb3React";
import { connectors } from "config/constants/connectors";

const Home: NextPage = () => {
  const { account, activate } = useActiveWeb3React();

  useEffect(() => {
    activate(connectors["injected"]);
  }, []);
  return (
    <div>
      <Head>
        <title>NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button
        onClick={() => {
          activate(connectors["injected"]);
        }}
      >
        connect{account}
      </Button>
    </div>
  );
};

export default Home;
